baseURL = "https://mydomain.org"
languageCode = "en-us"
title = "Simple Hugo"

[permalinks]
  blog = "/:title/"

[[params.links.developer]]
  name = "Developer Help"
  url = "mailto:developers-help@<our_domain>.com"
  icon = "fa fa-envelope"
  desc = "Ask questions about the our SDK"
